; -------------------------------------
; DOS Build Definitions
; -------------------------------------

REL_COUNT	                    EQU 11

REL_YEAR	                    EQU 2024
REL_MONTH	                    EQU 05
REL_DAY		                    EQU 21

REL_HOUR	                    EQU 10
REL_MINUTE	                    EQU 30
REL_SECOND	                    EQU 00

REL_DAYCOUNT	                EQU 113

